line-length = 79

[lint]
select = [
"A", "AIR", "ANN", "ARG", "ASYNC", "B", "BLE", "C4", "C90", "COM", "D", "DJ", "DTZ", "E", "EM", "ERA", "EXE", "F", "FA", "FIX", "FLY", "G", "I", "ICN", "INP", "INT", "ISC", "N", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "Q", "RET", "RSE", "RUF", "S", "SIM", "SLF", "T10", "T20", "TCH", "TD", "TID", "TRY", "UP", "YTT"
]

ignore = [
    "PLR2004",  # Magic value used in comparison, consider replacing with a constant variable
    "D107",     # Missing docstring in `__init__`
    "D202",     # No blank lines allowed after function docstring
    "D203",     # one-blank-line-before-class
    "D212",     # multi-line-summary-second-line
    "Q002",     # Double quote docstring found but single quotes preferred
    "RET504",   # Unnecessary variable assignment before `return` statement
    "ANN401",   # Dynamically typed expressions (typing.Any) are disallowed in `**kwargs`
    "PTH123",   # `open()` should be replaced by `Path.open()`
    "G004",     # Logging statement uses f-string
    "TCH002",   # Move third-party import into a type-checking block
    "TCH003"    # Move standard library import into a type-checking block
]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "venv",
]

flake8-quotes.inline-quotes = "single"
flake8-quotes.docstring-quotes = "single"

[lint.mccabe]
max-complexity = 5

[lint.per-file-ignores]
"tests/**.py" = [
    "D",
    "ANN",
    "S101",
    "PT003",   # `scope='function'` is implied in `@pytest.fixture()`
    "SLF001",  # Private member accessed
    "S311",    # Standard pseudo-random generators aren't good for cryptography
]
"*/__init__.py" = ["D"]
